version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  express-api:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./express-api:/usr/src/app
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER_FILE: /run/secrets/mysql_user
      DB_PASSWORD_FILE: /run/secrets/mysql_password
      DB_NAME_FILE: /run/secrets/mysql_database
      ACCESS_TOKEN_SECRET_FILE: /run/secrets/access_token_secret
      NODE_ENV: production
    networks:
      - backend_network
    secrets:
      - mysql_user
      - mysql_password
      - mysql_database
      - access_token_secret
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - backend_network
    secrets:
      - mysql_root_password
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:

networks:
  backend_network:
    driver: overlay

secrets:
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  mysql_user:
    external: true
  mysql_password:
    external: true
  access_token_secret:
    external: true
